### PR TITLE
Modifying openshift-spark so that it mirrors xpaas-spark

### PR DESCRIPTION
**Pull request by crobby**
in the way that it starts.  It now uses the env var
SPARK_MASTER_ADDRESS to determine whether to launch
as a master (no SPARK_MASTER_ADDRESS present) or a
worker (SPARK_MASTER_ADDRESS set to the spark master).

### CODE REVIEW

**Comment by elmiko** [comment]
this looks good, i wonder if we should remove `common.sh`, `start-worker`, and `start-master` as well?

**Comment by tmckayus** [comment]
looks like we need to remove start commands from template.yaml, and set launch.sh to +x in the install script.

**Comment by tmckayus** [comment]
oh, and the template.yaml needs to set the env for the spark master in the spark worker pods

**Comment by crobby** [comment]
Good catches, I didn't try any of this outside of oshinko.  Thanks for trying out template.yaml!

**Comment by tmckayus** [comment]
lgtm, merging since we've put in the altered oshinko-rest already

**Pull request merged**
